# Generated by Django 3.1.4 on 2020-12-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A1', '0004_auto_20201212_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tags',
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='A1.Tag'),
        ),
    ]
