# Generated by Django 3.1.4 on 2020-12-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A1', '0007_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
